install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex
    - sudo apt-get install aspell 
    - sudo apt-get install xelatex 

script:
    - make
    - chktex -W # Print version information.
    - chktex -q -n 6 *.tex chapters.*.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out
    # Spell check
    - aspell --home-dir=. --personal=.aspell.en.pws --lang=en list -t < cv.tex | tee spell.out
    - test ! -s spell.out
